# Generated by Django 5.1.4 on 2024-12-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpgstoneuk', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the logo.', max_length=255, null=True)),
                ('image', models.ImageField(help_text='Upload the logo image.', upload_to='logos/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for the logo.', max_length=255, null=True)),
            ],
        ),
    ]
