# Generated by Django 5.1.4 on 2024-12-31 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpgstoneuk', '0004_alter_logo_alt_text_alter_logo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The display name of the menu item.', max_length=100)),
                ('url', models.CharField(blank=True, help_text='URL or path for the menu item.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the menu item.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the menu item is active.')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item, if any (for dropdown menus).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mpgstoneuk.menuitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
