# Generated by Django 5.1.4 on 2024-12-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpgstoneuk', '0008_remove_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
