# Generated by Django 5.1.4 on 2024-12-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpgstoneuk', '0009_menuitem_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=50)),
                ('url', models.URLField()),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('both', 'Both')], default='both', max_length=10)),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
