# Generated by Django 5.1.4 on 2025-01-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpgstoneuk', '0011_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mpgstoneuk.product'),
            preserve_default=False,
        ),
    ]
