# Generated by Django 5.1.4 on 2025-01-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpgstoneuk', '0012_productcomment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique URL identifier', unique=True)),
                ('title', models.CharField(help_text='Page title', max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='Meta title for SEO', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('content', models.TextField(help_text='Page content')),
            ],
        ),
    ]
