# Generated by Django 5.1.4 on 2025-01-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpgstoneuk', '0019_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='URL or path for the menu item.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pagestitle',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL identifier', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
