# Generated by Django 5.1.4 on 2025-01-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpgstoneuk', '0020_alter_category_slug_alter_menuitem_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL identifier', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.SlugField(blank=True, help_text='URL or path for the menu item.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL identifier', max_length=200, unique=True),
        ),
    ]
